apiVersion: v1
kind: Service
metadata:
  name: fakerai-service-api
  labels:
    app: fakerai-service-api
spec:
  type: NodePort
  selector:
    app: fakerai-service-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
